version : '2'
networks:
  sdv-net:
    external:
      name: sdv-net
services:
  nginx:
      image: nginx:stable
      container_name: sdv-nginx
      ports:
        - "3000:80"
      volumes:
        - ./:/var/www/html/
        - ./default.conf:/etc/nginx/conf.d/default.conf
      external_links:
        - sdv-admin
      networks:
        - sdv-net
  php:
      build: ./php
      container_name: sdv-admin
      volumes:
        - ./:/var/www/html/
      networks:
        - sdv-net
      
  